name: Deploy to pypi

on:
  pull_request:
    types: closed
    branches:
      - master
    paths:
          - 'gradio/version.txt'

jobs:
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
